import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter,NavLink,Route,Routes,Link,useParams}from'react-router-dom';import{House,Flag,Medal,MapPinned,UserRound,MapPin,CalendarDays,Users}from'lucide-react';import'./style.css';
type Race={id:string;title:string;track:string;place:string;date:string;format:string;fee:number;registered:number;capacity:number;mode:'BOOKING'|'LISTED';image:string};
const races:Race[]=[{id:'pomposa-500',title:'500 Miglia di Pomposa',track:'Circuito di Pomposa',place:'Pomposa (FE)',date:'14 novembre 2026 · 09:00',format:'Endurance · 6h',fee:600,registered:18,capacity:24,mode:'BOOKING',image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80'},{id:'lonato-sprint',title:'SWS Sprint Night',track:'South Garda Karting',place:'Lonato (BS)',date:'28 novembre 2026 · 18:30',format:'Sprint · 2x15m',fee:85,registered:20,capacity:30,mode:'LISTED',image:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80'}];
function Card({r}:{r:Race}){return <article className="race"><img src={r.image} alt="Circuito kart"/><div className="pad"><em>{r.mode==='BOOKING'?'BOOKING KARTHUB':'ISCRIZIONE ESTERNA'}</em><h3>{r.title}</h3><p><MapPin/> {r.track}</p><p><CalendarDays/> {r.date}</p><p><Users/> {r.registered}/{r.capacity} iscritti</p><footer><b>€ {r.fee}</b><Link to={'/gare/'+r.id}>Dettagli</Link></footer></div></article>}
function Home(){return <><section className="hero"><div><em>LA COMMUNITY DEL RENTAL KARTING</em><h1>WIN<br/><span>TOGETHER.</span></h1><p>Più di una gara. Una community.</p><Link to="/gare" className="cta">Scopri le gare →</Link></div></section><section className="metrics"><div><b>48</b><small>Gare in arrivo</small></div><div><b>1.2K</b><small>Piloti attivi</small></div><div><b>86</b><small>Piste in Italia</small></div></section><Title t="Prossime gare"/><div className="cards">{races.map(r=><Card r={r} key={r.id}/>)}</div><Title t="Attività della community"/><div className="feed"><div className="avatar">MR</div><div><b>Marco_Race27</b><p>Nuovo best lap al Circuito di Pomposa. Sempre più gas!</p><small>2 ore fa</small></div></div></>}
function Title({t}:{t:string}){return <div className="title"><h2>{t}</h2><span>Vedi tutte →</span></div>}
function Gare(){return <section><header className="page"><em>DISCOVERY</em><h1>Gare</h1><p>Eventi selezionati, booking diretto o iscrizione presso l'organizzatore.</p></header><div className="chips"><button>Tutte</button><button>Sprint</button><button>Endurance</button><button>Ironman</button></div><div className="cards">{races.map(r=><Card r={r} key={r.id}/>)}</div></section>}
function Detail(){const{id}=useParams();const r=races.find(x=>x.id===id);if(!r)return <h1>Gara non trovata</h1>;return <section><Link className="back" to="/gare">← Tutte le gare</Link><div className="detail" style={{backgroundImage:`linear-gradient(0deg,#080b0e,transparent),url(${r.image})`}}><div><em>{r.mode}</em><h1>{r.title}</h1><p>{r.track} · {r.place}</p></div></div><div className="columns"><article className="panel"><h2>Informazioni</h2><p>{r.date}</p><p>{r.format}</p><p>{r.registered}/{r.capacity} iscritti</p></article><article className="panel"><em>QUOTA</em><h2>€ {r.fee}</h2><button className="wide">{r.mode==='BOOKING'?'Richiedi iscrizione':'Vai all’organizzatore'}</button><small>Versione Alpha: nessun pagamento viene effettuato.</small></article></div></section>}
function Ranking(){let x=[['1','Andrea Rossi','1840'],['2','Giulia Riva','1715'],['3','Luca Bianchi','1690'],['12','Antonio Santoro','980']];return <section><header className="page"><em>ITALIA 2026</em><h1>Ranking</h1><p>Classifica dimostrativa basata su risultati verificati.</p></header><div className="ranking">{x.map((a,i)=><div className={i===3?'me':''}><b>#{a[0]}</b><div className="avatar">{a[1].split(' ').map(z=>z[0]).join('')}</div><strong>{a[1]}</strong><span>{a[2]} pt</span></div>)}</div></section>}
function Mappa(){return <section><header className="page"><em>PISTE</em><h1>Mappa</h1><p>Scopri piste ed eventi vicini.</p></header><div className="map"><i className="p1">K</i><i className="p2">K</i><span>Italia settentrionale</span></div></section>}
function Profilo(){return <section><div className="cover"><div className="avatar big">AS</div></div><div className="profile"><div><h1>Antonio Santoro</h1><p>@antonio · Emilia-Romagna</p></div><button>Modifica</button></div><div className="metrics"><div><b>12</b><small>Gare</small></div><div><b>3</b><small>Podi</small></div><div><b>980</b><small>Punti</small></div></div><article className="panel"><em>GARAGE</em><h2>La tua identità in pista</h2><p>Completa il profilo, segui altri piloti e collega i risultati verificati.</p></article></section>}
function Layout(){return <div className="shell"><header className="top"><div className="logo">KART<span>HUB.</span></div><div className="beta">ITALIA · ALPHA</div></header><main><Routes><Route path="/" element={<Home/>}/><Route path="/gare" element={<Gare/>}/><Route path="/gare/:id" element={<Detail/>}/><Route path="/ranking" element={<Ranking/>}/><Route path="/mappa" element={<Mappa/>}/><Route path="/profilo" element={<Profilo/>}/></Routes></main><nav>{[['/',House,'Home'],['/gare',Flag,'Gare'],['/ranking',Medal,'Classifiche'],['/mappa',MapPinned,'Mappa'],['/profilo',UserRound,'Profilo']].map(([to,I,l]:any)=><NavLink to={to} end={to==='/' }><I/><small>{l}</small></NavLink>)}</nav></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><Layout/></BrowserRouter></React.StrictMode>);
