create type public.user_role as enum ('driver','organizer','admin');
create type public.registration_mode as enum ('listed','karthub_booking');
create table public.profiles (id uuid primary key references auth.users on delete cascade, username text unique not null, full_name text, city text, bio text, avatar_url text, role public.user_role not null default 'driver', created_at timestamptz not null default now());
create table public.tracks (id uuid primary key default gen_random_uuid(), name text not null, city text, region text, latitude double precision, longitude double precision, image_url text, created_at timestamptz not null default now());
create table public.organizers (id uuid primary key default gen_random_uuid(), name text not null, website text, created_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), organizer_id uuid references public.organizers, track_id uuid references public.tracks, title text not null, starts_at timestamptz not null, format text not null, entry_fee_cents integer not null default 0 check(entry_fee_cents>=0), capacity integer not null check(capacity>0), registration_mode public.registration_mode not null default 'listed', external_url text, status text not null default 'draft', created_at timestamptz not null default now());
create table public.follows (follower_id uuid references public.profiles on delete cascade, following_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(follower_id,following_id), check(follower_id<>following_id));
create table public.registrations (id uuid primary key default gen_random_uuid(), event_id uuid references public.events on delete cascade, user_id uuid references public.profiles on delete cascade, status text not null default 'pending', created_at timestamptz not null default now(), unique(event_id,user_id));
create table public.results (id uuid primary key default gen_random_uuid(), event_id uuid references public.events on delete cascade, user_id uuid references public.profiles on delete cascade, position integer check(position>0), points integer not null default 0, verified boolean not null default false);
alter table public.profiles enable row level security; alter table public.tracks enable row level security; alter table public.organizers enable row level security; alter table public.events enable row level security; alter table public.follows enable row level security; alter table public.registrations enable row level security; alter table public.results enable row level security;
create policy "Public profiles readable" on public.profiles for select using (true);
create policy "Own profile editable" on public.profiles for update using (auth.uid()=id);
create policy "Tracks readable" on public.tracks for select using (true);
create policy "Organizers readable" on public.organizers for select using (true);
create policy "Published events readable" on public.events for select using (status='published');
create policy "Results readable" on public.results for select using (verified=true);
create policy "Own follows manageable" on public.follows for all using (auth.uid()=follower_id) with check (auth.uid()=follower_id);
create policy "Own registrations readable" on public.registrations for select using (auth.uid()=user_id);
